const ACTION_TYPES = {
  CREATE_TASK_ACTION: 'CREATE_TASK_ACTION',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_TASKS_ACTION: 'GET_TASKS_ACTION',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',

  DELETE_TASK_ACTION: 'DELETE_TASK_ACTION',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',

  TOGGLE_IS_EDIT_TASK: 'TOGGLE_IS_EDIT_TASK'
};

export default ACTION_TYPES;
